---
- hosts: [stagesherlock]
  sudo: True
  remote_user: odadmin
  vars:
    data_dir: /data
  
  pre_tasks:
    - name: apt-get update and upgrade 
      apt: update_cache=yes
      apt: upgrade=yes
    - name: install things
      apt: name=etckeeper,nscd,htop state=installed

  tasks:
    - name: Improve Host file
      lineinfile:
        dest: /etc/hosts
        line: '{{ansible_default_ipv4.address}} {{ansible_hostname}}.hq.overdrive.com {{ansible_hostname}}'
        insertbefore: '^127.0.0.1'

    - shell: /bin/true
      register: normal_task_list

    - name: Configure data partition if data drive exists
      shell: echo -e "n\n\n\n\n\nw" | sudo fdisk /dev/sdb && sudo mkfs.ext4 /dev/sdb1
      args:
        executable: /bin/bash
      when: normal_task_list is not defined
      tags:
        - b

    - name: Configure data partition if data drive exists
      shell: echo -e "n\n\n\n\n\nw" | sudo fdisk /dev/sdc && sudo mkfs.ext4 /dev/sdc1
      args:
        executable: /bin/bash
      when: normal_task_list is not defined
      tags:
        - c

    - name: Configure data partition if data drive exists
      shell: echo -e "n\n\n\n\n\nw" | sudo fdisk /dev/sdd && sudo mkfs.ext4 /dev/sdd1
      args:
        executable: /bin/bash
      when: normal_task_list is not defined
      tags:
        - d

    - name: Configure data partition if data drive exists
      shell: echo -e "n\n\n\n\n\nw" | sudo fdisk /dev/sde && sudo mkfs.ext4 /dev/sde1
      args:
        executable: /bin/bash
      when: normal_task_list is not defined
      tags:
        - e

    - name: Get blkid output
      shell: blkid /dev/sdb1 | awk -F "\"" '{print $2}'
      register: uuid
      when: normal_task_list is not defined
      tags:
        - b

    - name: Get blkid output
      shell: blkid /dev/sdc1 | awk -F "\"" '{print $2}'
      register: uuid
      when: normal_task_list is not defined
      tags:
        - c

    - name: Get blkid output
      shell: blkid /dev/sdd1 | awk -F "\"" '{print $2}'
      register: uuid
      when: normal_task_list is not defined
      tags:
        - d

    - name: Get blkid output
      shell: blkid /dev/sde1 | awk -F "\"" '{print $2}'
      register: uuid
      when: normal_task_list is not defined
      tags:
        - e

    - name: Insert to etc fstab to mount
      lineinfile:
        dest: /etc/fstab
        line: 'UUID={{ uuid.stdout }} {{data_dir}} ext4 defaults 0 0'
      when: normal_task_list is not defined
      tags:
        - b
        - c
        - d
        - e

    - name: Create the mount directory
      file:
        path: "{{data_dir}}"
        state: directory
        mode: 0755
      when: normal_task_list is not defined
      tags:
        - b
        - c
        - d
        - e

    - name: mount
      shell: mount -a
      when: normal_task_list is not defined
      tags:
        - b
        - c
        - d
        - e

  roles:
    - franklinkim.ntp
    - wrboyce.snmpd
